"""add intelligence persistence tables

Revision ID: bd243482c8a0
Revises: 
Create Date: 2026-05-08 18:28:14.506118+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

CURRENT_TIMESTAMP_SQL = '(CURRENT_TIMESTAMP)'
WORKFLOW_RUNS_ID = 'workflow_runs.id'



# revision identifiers, used by Alembic.
revision: str = 'bd243482c8a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('repo_url', sa.String(length=512), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('github_token', sa.Text(), nullable=True),
    sa.Column('connection_status', sa.Enum('PENDING', 'CONNECTED', 'FAILED', 'DISCONNECTED', name='connection_status_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('github_repo_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_branch', sa.String(length=255), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('stars_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name')
    )
    op.create_index(op.f('ix_repositories_connection_status'), 'repositories', ['connection_status'], unique=False)
    op.create_index(op.f('ix_repositories_name'), 'repositories', ['name'], unique=False)
    op.create_index(op.f('ix_repositories_owner'), 'repositories', ['owner'], unique=False)
    op.create_index(op.f('ix_repositories_repo_url'), 'repositories', ['repo_url'], unique=True)
    op.create_table('commits',
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('sha', sa.String(length=40), nullable=False),
    sa.Column('short_sha', sa.String(length=10), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('author_email', sa.String(length=320), nullable=True),
    sa.Column('authored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('files_changed', sa.Integer(), nullable=True),
    sa.Column('additions', sa.Integer(), nullable=True),
    sa.Column('deletions', sa.Integer(), nullable=True),
    sa.Column('is_merge_commit', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commits_authored_at'), 'commits', ['authored_at'], unique=False)
    op.create_index(op.f('ix_commits_branch'), 'commits', ['branch'], unique=False)
    op.create_index(op.f('ix_commits_repository_id'), 'commits', ['repository_id'], unique=False)
    op.create_index(op.f('ix_commits_sha'), 'commits', ['sha'], unique=True)
    op.create_table('workflow_runs',
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('commit_id', sa.UUID(), nullable=True),
    sa.Column('github_run_id', sa.Integer(), nullable=False),
    sa.Column('workflow_name', sa.String(length=512), nullable=False),
    sa.Column('workflow_path', sa.String(length=512), nullable=True),
    sa.Column('head_branch', sa.String(length=255), nullable=True),
    sa.Column('head_sha', sa.String(length=40), nullable=True),
    sa.Column('run_number', sa.Integer(), nullable=True),
    sa.Column('run_attempt', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', 'SKIPPED', name='workflow_run_status_enum'), nullable=False),
    sa.Column('conclusion', sa.Enum('SUCCESS', 'FAILURE', 'NEUTRAL', 'CANCELLED', 'SKIPPED', 'TIMED_OUT', 'ACTION_REQUIRED', name='workflow_run_conclusion_enum'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('triggering_actor', sa.String(length=255), nullable=True),
    sa.Column('html_url', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.ForeignKeyConstraint(['commit_id'], ['commits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_run_id')
    )
    op.create_index(op.f('ix_workflow_runs_commit_id'), 'workflow_runs', ['commit_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_conclusion'), 'workflow_runs', ['conclusion'], unique=False)
    op.create_index(op.f('ix_workflow_runs_repository_id'), 'workflow_runs', ['repository_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_status'), 'workflow_runs', ['status'], unique=False)
    op.create_table('deployment_outcomes',
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.Enum('SUCCESS', 'FAILURE', 'ROLLBACK', 'PARTIAL', name='outcome_label_enum'), nullable=False),
    sa.Column('was_rolled_back', sa.Boolean(), nullable=False),
    sa.Column('rollback_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('incident_created', sa.Boolean(), nullable=False),
    sa.Column('incident_id', sa.String(length=255), nullable=True),
    sa.Column('downtime_seconds', sa.Integer(), nullable=True),
    sa.Column('error_rate_spike', sa.Float(), nullable=True),
    sa.Column('latency_spike_ms', sa.Float(), nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], [WORKFLOW_RUNS_ID], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_outcomes_label'), 'deployment_outcomes', ['label'], unique=False)
    op.create_index(op.f('ix_deployment_outcomes_workflow_run_id'), 'deployment_outcomes', ['workflow_run_id'], unique=True)
    op.create_table('extracted_features',
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('files_changed', sa.Integer(), nullable=True),
    sa.Column('additions', sa.Integer(), nullable=True),
    sa.Column('deletions', sa.Integer(), nullable=True),
    sa.Column('prior_failure_rate', sa.Float(), nullable=True),
    sa.Column('avg_duration_seconds', sa.Float(), nullable=True),
    sa.Column('time_since_last_run_seconds', sa.Float(), nullable=True),
    sa.Column('concurrent_runs', sa.Integer(), nullable=True),
    sa.Column('days_since_last_success', sa.Float(), nullable=True),
    sa.Column('feature_version', sa.String(length=50), nullable=False),
    sa.Column('feature_vector', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], [WORKFLOW_RUNS_ID], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_features_workflow_run_id'), 'extracted_features', ['workflow_run_id'], unique=True)
    op.create_table('predictions',
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('failure_probability', sa.Float(), nullable=False),
    sa.Column('predicted_label', sa.String(length=50), nullable=False),
    sa.Column('raw_output', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], [WORKFLOW_RUNS_ID], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_workflow_run_id'), 'predictions', ['workflow_run_id'], unique=False)
    op.create_table('feature_contributions',
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('feature_name', sa.String(length=255), nullable=False),
    sa.Column('feature_value', sa.Float(), nullable=True),
    sa.Column('contribution_value', sa.Float(), nullable=False),
    sa.Column('impact_percent', sa.Float(), nullable=True),
    sa.Column('contribution_rank', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_contributions_prediction_id'), 'feature_contributions', ['prediction_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='recommendation_priority_enum'), nullable=False),
    sa.Column('status', sa.Enum('GENERATED', 'ACKNOWLEDGED', 'APPLIED', 'DISMISSED', name='recommendation_status_enum'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_prediction_id'), 'recommendations', ['prediction_id'], unique=False)
    op.create_index(op.f('ix_recommendations_priority'), 'recommendations', ['priority'], unique=False)
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_priority'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_prediction_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_feature_contributions_prediction_id'), table_name='feature_contributions')
    op.drop_table('feature_contributions')
    op.drop_index(op.f('ix_predictions_workflow_run_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_extracted_features_workflow_run_id'), table_name='extracted_features')
    op.drop_table('extracted_features')
    op.drop_index(op.f('ix_deployment_outcomes_workflow_run_id'), table_name='deployment_outcomes')
    op.drop_index(op.f('ix_deployment_outcomes_label'), table_name='deployment_outcomes')
    op.drop_table('deployment_outcomes')
    op.drop_index(op.f('ix_workflow_runs_status'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_repository_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_conclusion'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_commit_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_commits_sha'), table_name='commits')
    op.drop_index(op.f('ix_commits_repository_id'), table_name='commits')
    op.drop_index(op.f('ix_commits_branch'), table_name='commits')
    op.drop_index(op.f('ix_commits_authored_at'), table_name='commits')
    op.drop_table('commits')
    op.drop_index(op.f('ix_repositories_repo_url'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_owner'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_name'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_connection_status'), table_name='repositories')
    op.drop_table('repositories')
    # ### end Alembic commands ###
