"""Add raw_payload to orchestration events

Revision ID: 65e010b2d904
Revises: 617ebb6134ac
Create Date: 2026-05-10 11:56:23.750524+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65e010b2d904'
down_revision: Union[str, None] = '617ebb6134ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orchestration_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_payload', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orchestration_events', schema=None) as batch_op:
        batch_op.drop_column('raw_payload')
    # ### end Alembic commands ###
