"""Add orchestration intelligence models

Revision ID: 617ebb6134ac
Revises: 84a4fd0d6d90
Create Date: 2026-05-10 11:45:08.256530+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

CURRENT_TIMESTAMP_SQL = CURRENT_TIMESTAMP_SQL



# revision identifiers, used by Alembic.
revision: str = '617ebb6134ac'
down_revision: Union[str, None] = '84a4fd0d6d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrations',
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('auth_config', sa.JSON(), nullable=True),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrations_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrations_tool_name'), ['tool_name'], unique=False)

    op.create_table('service_registry',
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('owning_team', sa.String(), nullable=True),
    sa.Column('criticality_level', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_registry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_registry_environment'), ['environment'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_registry_service_name'), ['service_name'], unique=True)

    op.create_table('operational_insights',
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('insight_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('supporting_event_ids', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operational_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operational_insights_insight_type'), ['insight_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_operational_insights_service_id'), ['service_id'], unique=False)

    op.create_table('orchestration_events',
    sa.Column('integration_id', sa.UUID(), nullable=True),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('normalized_data', sa.JSON(), nullable=False),
    sa.Column('operational_impact', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orchestration_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orchestration_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_orchestration_events_integration_id'), ['integration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orchestration_events_service_id'), ['service_id'], unique=False)

    op.create_table('context_relations',
    sa.Column('source_event_id', sa.UUID(), nullable=False),
    sa.Column('related_event_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('impact_level', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text(CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text(CURRENT_TIMESTAMP_SQL), nullable=False),
    sa.ForeignKeyConstraint(['related_event_id'], ['orchestration_events.id'], ),
    sa.ForeignKeyConstraint(['source_event_id'], ['orchestration_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('context_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_context_relations_related_event_id'), ['related_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_context_relations_source_event_id'), ['source_event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('context_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_context_relations_source_event_id'))
        batch_op.drop_index(batch_op.f('ix_context_relations_related_event_id'))

    op.drop_table('context_relations')
    with op.batch_alter_table('orchestration_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orchestration_events_service_id'))
        batch_op.drop_index(batch_op.f('ix_orchestration_events_integration_id'))
        batch_op.drop_index(batch_op.f('ix_orchestration_events_event_type'))

    op.drop_table('orchestration_events')
    with op.batch_alter_table('operational_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operational_insights_service_id'))
        batch_op.drop_index(batch_op.f('ix_operational_insights_insight_type'))

    op.drop_table('operational_insights')
    with op.batch_alter_table('service_registry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_registry_service_name'))
        batch_op.drop_index(batch_op.f('ix_service_registry_environment'))

    op.drop_table('service_registry')
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrations_tool_name'))
        batch_op.drop_index(batch_op.f('ix_integrations_category'))

    op.drop_table('integrations')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
