import type {
  DeploymentHistory,
  TelemetryData,
  ActivityFeedItem,
  SummaryStats,
  Recommendation,
} from './api-types'

export const mockSummaryStats: SummaryStats = {
  total_runs: 1248,
  critical_deployments: 12,
  average_risk_score: 42.3,
  active_alerts: 5,
}

export const mockDeploymentHistory: DeploymentHistory[] = [
  {
    id: '1',
    repository: 'frontend-app',
    run_id: 'GH-2024-001',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    severity: 'MEDIUM',
    risk_score: 45,
    branch: 'main',
    commit_sha: 'abc123def456',
  },
  {
    id: '2',
    repository: 'api-service',
    run_id: 'GH-2024-002',
    timestamp: "2024-05-09T07:00:00Z",
    severity: 'LOW',
    risk_score: 22,
    branch: 'develop',
    commit_sha: 'def456ghi789',
  },
  {
    id: '3',
    repository: 'auth-service',
    run_id: 'GH-2024-003',
    timestamp: "2024-05-09T04:00:00Z",
    severity: 'CRITICAL',
    risk_score: 78,
    branch: 'main',
    commit_sha: 'ghi789jkl012',
  },
  {
    id: '4',
    repository: 'database-migration',
    run_id: 'GH-2024-004',
    timestamp: "2024-05-09T01:00:00Z",
    severity: 'HIGH',
    risk_score: 62,
    branch: 'feature/db-optimization',
    commit_sha: 'jkl012mno345',
  },
  {
    id: '5',
    repository: 'monitoring-service',
    run_id: 'GH-2024-005',
    timestamp: "2024-05-08T12:00:00Z",
    severity: 'LOW',
    risk_score: 18,
    branch: 'main',
    commit_sha: 'mno345pqr678',
  },
  {
    id: '6',
    repository: 'payment-processor',
    run_id: 'GH-2024-006',
    timestamp: "2024-05-08T00:00:00Z",
    severity: 'HIGH',
    risk_score: 55,
    branch: 'develop',
    commit_sha: 'pqr678stu901',
  },
  {
    id: '7',
    repository: 'cache-layer',
    run_id: 'GH-2024-007',
    timestamp: "2024-05-07T12:00:00Z",
    severity: 'MEDIUM',
    risk_score: 38,
    branch: 'optimization',
    commit_sha: 'stu901uvw234',
  },
  {
    id: '8',
    repository: 'notification-service',
    run_id: 'GH-2024-008',
    timestamp: "2024-05-06T12:00:00Z",
    severity: 'LOW',
    risk_score: 15,
    branch: 'main',
    commit_sha: 'uvw234vxy567',
  },
]

export const mockTelemetryData: TelemetryData[] = [
  {
    workflow_run_id: '5c21504d-9383-4419-ab64-cba3e6d7dfdb',
    source: 'github',
    workflow_name: 'Build and Deploy - Main',
    status: 'success',
    timestamp: "2024-05-09T11:00:00Z",
    duration: 245,
    runs_count: 856,
  },
  {
    workflow_run_id: '21aa7db1-3904-47cb-9570-7beb924b7941',
    source: 'github',
    workflow_name: 'Run Tests - PR',
    status: 'success',
    timestamp: "2024-05-09T10:00:00Z",
    duration: 320,
    runs_count: 1203,
  },
  {
    workflow_run_id: '94bb85ec-1e25-45ae-974b-f665c8933b81',
    source: 'jenkins',
    workflow_name: 'Nightly Build',
    status: 'running',
    timestamp: "2024-05-09T12:00:00Z",
    duration: 0,
    runs_count: 45,
  },
  {
    workflow_run_id: '9fe692f8-40e5-419e-87a4-1bc65c7919a2',
    source: 'jenkins',
    workflow_name: 'Security Scan',
    status: 'success',
    timestamp: "2024-05-09T08:00:00Z",
    duration: 180,
    runs_count: 124,
  },
  {
    workflow_run_id: '6c1c615c-e09d-4f5d-afe1-d8defb142e73',
    source: 'github',
    workflow_name: 'Deploy to Staging',
    status: 'success',
    timestamp: "2024-05-09T06:00:00Z",
    duration: 520,
    runs_count: 267,
  },
]

export const mockActivityFeed: ActivityFeedItem[] = [
  {
    id: '1',
    type: 'analysis',
    title: 'High Risk Analysis Completed',
    description: 'auth-service deployment flagged with 78% risk score',
    severity: 'CRITICAL',
    timestamp: "2024-05-09T12:10:00Z",
  },
  {
    id: '2',
    type: 'deployment',
    title: 'Deployment Successful',
    description: 'frontend-app v2.4.1 deployed to production',
    severity: 'LOW',
    timestamp: "2024-05-09T12:00:00Z",
  },
  {
    id: '3',
    type: 'alert',
    title: 'Performance Alert',
    description: 'Response time exceeded threshold on API service',
    severity: 'HIGH',
    timestamp: "2024-05-09T11:45:00Z",
  },
  {
    id: '4',
    type: 'analysis',
    title: 'Low Risk Analysis',
    description: 'monitoring-service deployment analysis complete',
    severity: 'LOW',
    timestamp: "2024-05-09T11:15:00Z",
  },
  {
    id: '5',
    type: 'deployment',
    title: 'Rollback Initiated',
    description: 'payment-processor reverted to v1.8.2',
    severity: 'HIGH',
    timestamp: "2024-05-09T10:15:00Z",
  },
]

export const mockRecommendations: Recommendation[] = [
  {
    id: '1',
    title: 'Reduce Cyclomatic Complexity',
    reason: 'The authentication service has complex decision trees with 28 branches',
    action_type: 'refactor',
    related_feature: 'CYCLO',
    severity: 'CRITICAL',
    priority: 1,
  },
  {
    id: '2',
    title: 'Split Large Functions',
    reason: 'Several functions exceed 600 lines, impacting maintainability',
    action_type: 'refactor',
    related_feature: 'LENGTH',
    severity: 'HIGH',
    priority: 2,
  },
  {
    id: '3',
    title: 'Add Unit Tests',
    reason: 'Test coverage is below 60% for critical paths',
    action_type: 'optimize',
    related_feature: 'test_coverage',
    severity: 'HIGH',
    priority: 3,
  },
  {
    id: '4',
    title: 'Reduce Coupling',
    reason: 'Payment service depends on 12 external modules',
    action_type: 'refactor',
    related_feature: 'INT_FAN_OUT',
    severity: 'MEDIUM',
    priority: 4,
  },
  {
    id: '5',
    title: 'Add Documentation',
    reason: 'Complex API endpoints lack proper documentation',
    action_type: 'document',
    related_feature: 'documentation',
    severity: 'MEDIUM',
    priority: 5,
  },
  {
    id: '6',
    title: 'Optimize Database Queries',
    reason: 'Several N+1 query patterns detected',
    action_type: 'optimize',
    related_feature: 'database_queries',
    severity: 'MEDIUM',
    priority: 6,
  },
  {
    id: '7',
    title: 'Fix Performance Bottleneck',
    reason: 'Caching layer could reduce latency by 40%',
    action_type: 'optimize',
    related_feature: 'performance',
    severity: 'MEDIUM',
    priority: 7,
  },
  {
    id: '8',
    title: 'Improve Error Handling',
    reason: 'Several exception handlers could be more specific',
    action_type: 'bug_fix',
    related_feature: 'error_handling',
    severity: 'LOW',
    priority: 8,
  },
]

export const mockSHAPData = {
  feature_importance: [
    { feature: 'CYCLO', importance: 0.18, direction: 'increase_risk' as const },
    { feature: 'LENGTH', importance: 0.15, direction: 'increase_risk' as const },
    { feature: 'DIFFICULTY', importance: 0.14, direction: 'increase_risk' as const },
    { feature: 'VOLUME', importance: 0.12, direction: 'increase_risk' as const },
    { feature: 'NUM_OPERATORS', importance: 0.11, direction: 'increase_risk' as const },
    { feature: 'INT_FAN_OUT', importance: 0.1, direction: 'increase_risk' as const },
    { feature: 'NUM_OPERANDS', importance: 0.09, direction: 'increase_risk' as const },
    { feature: 'INT_FAN_IN', importance: 0.08, direction: 'decrease_risk' as const },
    { feature: 'BRANCH_COUNT', importance: 0.03, direction: 'increase_risk' as const },
  ],
}

export const mockIntegrations = [
  {
    name: 'Prometheus',
    description: 'Metrics monitoring and alerting',
    status: 'connected' as const,
    last_sync: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    health: 'healthy' as const,
  },
  {
    name: 'Grafana',
    description: 'Visualization and dashboards',
    status: 'connected' as const,
    last_sync: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    health: 'healthy' as const,
  },
  {
    name: 'Kibana',
    description: 'Log analysis and visualization',
    status: 'connected' as const,
    last_sync: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    health: 'degraded' as const,
  },
  {
    name: 'Jaeger',
    description: 'Distributed tracing',
    status: 'connected' as const,
    last_sync: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    health: 'healthy' as const,
  },
  {
    name: 'SonarQube',
    description: 'Code quality analysis',
    status: 'connected' as const,
    last_sync: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    health: 'healthy' as const,
  },
  {
    name: 'Snyk',
    description: 'Security vulnerability scanning',
    status: 'disconnected' as const,
  },
  {
    name: 'Docker',
    description: 'Container management',
    status: 'connected' as const,
    last_sync: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    health: 'healthy' as const,
  },
  {
    name: 'Kubernetes',
    description: 'Orchestration platform',
    status: 'connected' as const,
    last_sync: new Date().toISOString(),
    health: 'healthy' as const,
  },
]
